carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar/', views.add, name='add'),
    path('eliminar/', views.remove, name='remove'),
]

products/urls.py
from django.urls import path
from .views import ProductDetailView, ProductSearchListView 

app_name = 'products'
urlpatterns = [
    
    path('search', ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>', ProductDetailView.as_view(), name='product')
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from products.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('carrito/', include('carts.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('orden/', include('orders.urls')),
    path('productos/', include('products.urls')),
    path('usuarios/login/', views.login_view, name='login'),
    path('usuarios/logout/', views.logout_view, name='logout'),
    path('usuarios/register/', views.register_view, name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
import uuid

class Product(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    slug = models.SlugField(null=False, blank=False, unique=True)
    image = models.ImageField(upload_to='products/', blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title)
    #     super(Product, self).save(*args, **kwargs)

    def __str__(self) :
        return self.title

def set_slug(sender, instance, *args, **kwargs):

    if instance.title and not instance.slug:
        slug = slugify(instance.title)

        while Product.objects.filter(slug=slug).exists():
            slug = slugify(
                '{}-{}'.format(instance.title, str(uuid.uuid4())[:8])
            )
        instance.slug = slug

pre_save.connect(set_slug, sender=Product)

products/views.py
from django.db.models.query import Q
from django.views.generic import ListView, DetailView
from .models import Product

class ProductListView(ListView):
    model = Product
    template_name = 'index.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
    
        context = super().get_context_data(**kwargs)
        context['message']= 'Listado de Productos' 
        return context
    
class ProductDetailView(DetailView):
    model = Product
    template_name  = 'products/product.html'
    

class ProductSearchListView(ListView):
    template_name = 'products/search.html'
    context_object_name = 'products'

    def get_queryset(self):
        filters = Q(title__icontains = self.query()) | Q(category__title__icontains = self.query())
        return Product.objects.filter(filters).distinct() #agregué distinct para evitar que me devuelva dos veces el mismo producto
    
    def query(self):
        return self.request.GET.get('q')

    def get_context_data(self, **kwargs):
    
        context = super().get_context_data(**kwargs)
        context['query']= self.query() 
        context['count']= context['products'].count()
        return context

products/templates/products/snippets/list.html
<div class="row">
    {% for product in products %}
<div class="col-3 mt-5">
  {% include 'products/snippets/product.html' %}
</div>
{% endfor %}
</div>

products/templates/products/snippets/product.html
<div class="card h-100">
    {% if product.image %}
    <img src="{{ product.image.url }}" alt="Imagen del producto" height="250" width="auto">
    {% endif %}
    <div class="card-body">
      <h5 class="card-title">
        {{ product.title | truncatechars:35 }}
      </h5>
      <p class="card-text">
        {{ product.description | truncatechars:45 }}
      </p>
      <a href="{% url 'products:product' product.slug %}" class="btn btn-primary">Ver detalle</a>
    </div>
  </div>

products/templates/products/snippets/search.html
<form action="{% url 'products:search' %}">
<div class="input-group">
    <input type="text" name="q" value="{{ query }}" placeholder="Buscar" class="form-control">
    <div class="input-group-append">
        <input type="submit" name="" value="Buscar" class="btn btn-primary">
    </div>
</div>
</form>