carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar/', views.add, name='add'),
    path('eliminar/', views.remove, name='remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmar', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
]

shipping_addresses/urls.py
from django.urls import path
from . import views 


app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('nuevo', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default')
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from products.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('carrito/', include('carts.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('orden/', include('orders.urls')),
    path('productos/', include('products.urls')),
    path('usuarios/login/', views.login_view, name='login'),
    path('usuarios/logout/', views.logout_view, name='logout'),
    path('usuarios/register/', views.register_view, name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from carts.models import Cart
from django.db import models
from django.db.models.signals import pre_save
from enum import Enum
from shipping_addresses.models import ShippingAddress
from users.models import User
import uuid

class OrderStatus(Enum):
    CREATED = 'CREATED'
    PAID = 'PAID'
    COMPLETED = 'COMPLETED'
    CANCELLED = 'CANCELLED'

choices = [ (tag, tag.value) for tag in OrderStatus]

class Order(models.Model):
    order_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, choices = choices, default='CREATED')
    shipping_total = models.DecimalField(max_digits=8, decimal_places=2, default=5)
    total = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    shipping_address = models.ForeignKey(ShippingAddress, blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.order_id
    
    def cancel(self):
        self.status = OrderStatus.CANCELLED
        self.save()
    
    def complete(self):
        self.status = OrderStatus.COMPLETED
        self.save()
    
    def get_or_set_shipping_address(self):
        if self.shipping_address:
            return self.shipping_address
        
        shipping_address = self.user.shipping_address
        if shipping_address:
            self.update_shipping_address(shipping_address)
            
        return shipping_address
    
    def update_shipping_address(self, shipping_address):
        self.shipping_address = shipping_address
        self.save()

    def update_total(self):
        self.total = self.get_total()
        self.save()
    
    def get_total(self):
        return self.cart.total + self.shipping_total
    
def set_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())

def set_total(sender, instance, *args, **kwargs):
    instance.total = instance.get_total()

pre_save.connect(set_order_id, sender=Order)
pre_save.connect(set_total, sender=Order)

orders/views.py
from carts.utils import get_or_create_cart, destroy_cart
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from shipping_addresses.models import ShippingAddress
from .mails import Mail
from .models import Order
from .utils import get_or_create_order, breadcrumb, destroy_order

@login_required(login_url='login')
def order(request):

    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)
    
    return render(request, 'orders/order.html', 
                  {'order': order, 
                   'cart': cart,
                   'breadcrumb': breadcrumb()})

@login_required(login_url='login')
def address(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)
    shipping_address = order.get_or_set_shipping_address()
    can_choose_address = request.user.shippingaddress_set.count() > 1

    return render(request, 'orders/address.html', {
        'order': order,
        'cart': cart,
        'breadcrumb': breadcrumb(address=True),
        'shipping_address': shipping_address,
        'can_choose_address': can_choose_address
    })

@login_required(login_url='login')
def select_address(request):
    shipping_addresses = request.user.shippingaddress_set.all()

    return render(request, 'orders/select_address.html', {
        'breadcrumb': breadcrumb(address=True),
        'shipping_addresses': shipping_addresses
    })

@login_required(login_url='login')
def check_address(request, pk):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)

    shipping_address = get_object_or_404(ShippingAddress, pk=pk)

    if request.user.id != shipping_address.user.id:
        return redirect('index')
    
    order.update_shipping_address(shipping_address)
    return redirect('orders:address')

@login_required(login_url='login')
def confirm(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)

    shipping_address = order.shipping_address

    if shipping_address is None:
        return redirect('orders:address')
    
    return  render(request, 'orders/confirm.html', {
        'order': order,
        'cart': cart,
        'breadcrumb': breadcrumb(confirmation=True),
        'shipping_address': shipping_address
    })

@login_required(login_url='login')
def cancel(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)

    if request.user.id != order.user.id:
        return redirect('carts:cart')
    order.cancel()
    destroy_cart(request)
    destroy_order(request)

    messages.error(request, 'Orden cancelada')
    return  redirect('index')

@login_required(login_url='login')
def complete(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)

    if request.user.id != order.user.id:
        return redirect('carts:cart')
    
    order.complete()
    Mail.send_complete_order(order, request.user)
    destroy_cart(request)
    destroy_order(request)
    
    messages.success(request, 'Orden completada exitosamente')
    return  redirect('index')

orders/templates/orders/address.html
{% extends 'base.html' %}
{% block breadcrumb %}
{% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}
{% block content %}
<div class="col">
    {% if shipping_address %}
    <div class="h3">
        Recibí el pedido en el punto de entrega
    </div>
    <div>
        {% include 'shipping_addresses/snippets/shipping_address.html' %}
        
        <div class="mt-2 d-inline-flex">
            <div class="">
            {% if can_choose_address %}
                <a href="{% url 'orders:select_address' %}" class="btn btn-info">Otra dirección</a>
            </div>
            {% endif %}
            <div>
                <a href="{% url 'orders:confirm' %}" class="btn btn-warning">Entregar en esta dirección</a>
            </div>
        </div>

    </div>
    {% else %}
    <div class="h3">
        Registra una dirección de envío
    </div>
    <div>
        {% url 'orders:address' as next_url %}
        <a href="{% url 'shipping_addresses:create' %}?next={{ next_url }}">Nueva dirección de envío</a>
    </div>
    {% endif %}
</div>
{% endblock %}

orders/templates/orders/confirm.html
{% extends 'base.html' %}
{% block breadcrumb %}
{% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}
{% block content %}
<div class="col-8">
    <div class="h3">
        Confirma tu pedido
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-4">
                    <div class="fw-bold">Dirección de envío</div>
                    <div class="card-text">{{ shipping_address.address }}</div>
                    <div class="card-text">{{ shipping_address.line1 }}</div>
                    <div class="card-text">{{ shipping_address.reference }}</div>
                    <div class="card-text">{{ shipping_address.postal_code }}</div>
                </div>
                <div class="col-4">
                    <div class="fw-bold">Método de pago</div>
                    <div class="card-text">tarjeta terminada en 4567</div>
                </div>
                <div class="col-4">
                    <div class="fw-bold">Código promocional</div>
                    <form>
                        <input type="text" value="" class="form-control" name="code">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="mt-3">
        <div class="card">
            <div class="card-body">
                {% for product in cart.products.all %}
                {% include 'orders/snippets/product.html' %}
                {% endfor %}  
            </div>
        </div>
    </div>
</div>
<div class="col">
    {% url 'orders:complete' as next_url %}
    {% include 'orders/snippets/resume.html' with next_url=next_url %}
    <div class="mt-2"><a href="{% url 'orders:cancel' %}" class="btn btn-danger">Cancelar el pedido</a></div>
</div>
{% endblock %}

orders/templates/orders/order.html
{% extends 'base.html' %}
{% block breadcrumb %}
{% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}
{% block content %}
<div class="col-8">
    <div class="h3">
        Revisa tu pedido
    </div>
    <div class="card">
        <div class="card-body">
            {% for product in cart.products.all %}
            {% include 'orders/snippets/product.html' %}
            {% endfor %}
        </div>
    </div>
</div>
<div class="col">
    {% url 'orders:address' as next_url %}
    {% include 'orders/snippets/resume.html' with next_url=next_url %}
</div>
{% endblock %}

orders/templates/orders/select_address.html
{% extends 'base.html' %}
{% block breadcrumb %}
{% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}
{% block content %}
<div class="col">
    <div class="h3">
        Selecciona una dirección de envío
    </div>
    <div class="mt-2">
        {% for shipping_address in shipping_addresses %}
        <div class="card mb-2">
            <div class="card-body">
                <h5 class="card-title">{{ shipping_address.address }}</h5>
                <p class="card-title">{{ shipping_address.postal_code }}</p>
                <a href="{% url 'orders:check_address' shipping_address.pk %}" class="btn btn-warning">Seleccionar</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}