carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar/', views.add, name='add'),
    path('eliminar/', views.remove, name='remove'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from products.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('carrito/', include('carts.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('orden/', include('orders.urls')),
    path('productos/', include('products.urls')),
    path('usuarios/login/', views.login_view, name='login'),
    path('usuarios/logout/', views.logout_view, name='logout'),
    path('usuarios/register/', views.register_view, name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from django.db.models.signals import pre_save, m2m_changed, post_save
from products.models import Product
from users.models import User
import uuid
import decimal

class Cart(models.Model):
    cart_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartProducts')
    subtotal = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
        
    FEE = 0.05

    def __str__(self):
        return self.cart_id
    
    def update_totals(self):
        self.update_subtotal()
        self.update_total()

        if self.order:
            self.order.update_total()


    def update_subtotal(self):
        # self.subtotal = sum([products.price for products in self.products.all()])
        # self.save()

        # actualizamos el calculo del subtotal multiplicando la cantidad de cada producto por el precio
        self.subtotal = sum([
            cp.quantity * cp.product.price for cp in self.products_related()
        ]) 
        self.save()

    def update_total(self):
        self.total = self.subtotal + (self.subtotal * decimal.Decimal(Cart.FEE))
        self.save()

    def products_related(self):
        return self.cartproducts_set.select_related('product')
    
    @property
    def order(self):
        return self.order_set.first()

class CartProductsManager(models.Manager):
    #con esta clase obtnemos o creamos un objeto cart. si ya esta creado se actualiza la cantida del product
    def create_or_update_quantity(self, cart, product, quantity=1):
        object, created = self.get_or_create(cart=cart, product=product)

        if not created:
            quantity = object.quantity + quantity
        object.update_quantity(quantity)    
        return object

class CartProducts(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    #lo traemos de cartProductsManager para actualizar la cantidad de producto
    objects = CartProductsManager()

    def update_quantity(self, quantity = 1):
        self.quantity = quantity
        self.save()

def set_cart_id(sender, instance, *args, **kwargs):
    if not instance.cart_id:
        instance.cart_id= str(uuid.uuid4())

def update_totals(instance, sender, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        instance.update_totals()

def post_save_update_totals(instance, sender, *args, **kwargs):
        instance.cart.update_totals()

pre_save.connect(set_cart_id, sender=Cart)
post_save.connect(post_save_update_totals, sender=CartProducts)
m2m_changed.connect(update_totals, sender=Cart.products.through)

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from products.models import Product
from .models import CartProducts
from .utils import get_or_create_cart


def cart(request):
    
    cart = get_or_create_cart(request)

    return render(request, 'carts/cart.html', {'cart': cart})

def add(request):

    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))
    quantity = int(request.POST.get('quantity', 1))

    # cart.products.add(product, through_defaults={
    #     'quantity': quantity
    # })
    #implementamos otra forma de crear la relacion entre carrito y productos
    cart_product = CartProducts.objects.create_or_update_quantity(cart=cart, product=product, quantity=quantity)
    #al hacerlo así se crea un nuevo item en el carrito (o sea que si agregamos más cantidad de un producto que
    # ya estaba en el carrito lo vamos a ver dos veces, por eso seguimos modificando el archivo .models creando
    # la clase CartProductManager)
    return render(request, 'carts/add.html', {
        'product': product,
        'cart_product' : cart_product,
        'quantity': quantity,
        })

def remove(request):
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))

    cart.products.remove(product)

    return redirect('carts:cart')

carts/templates/carts/snippets/add.html
<form action="{% url 'carts:add' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id }}">
    <div class="d-flex flex-row">
        <button type="button" class="btn btn-info" id="restar">-</button>
        <input type="number" value="1" class="col-1 text-align-center" id="cantidad" name="quantity" readonly>
        <button type="button" class="btn btn-info " id="sumar">+</button>
    </div>
    <div class="mt-2">
        <button type="submit" class="btn btn-warning">Agregar al carrito</button>
    </div>
</form>

<script>
    const sumar = document.getElementById("sumar");
    const restar = document.getElementById("restar");
    cantidad = document.getElementById("cantidad");

    sumar.addEventListener("click", function() {
        cantidad.value = parseInt(cantidad.value) + 1;
    })

    restar.addEventListener("click", function() {
        
        value = parseInt(cantidad.value);
        if (value > 1) {
            value = value - 1;
        }

        cantidad.value = value;
    })



</script>

carts/templates/carts/snippets/remove.html
<form action="{% url 'carts:remove' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id }}">
    <button type="submit" class="h6 fw-bold btn text-danger" style="padding:0px">Eliminar</button>
</form>