carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar/', views.add, name='add'),
    path('eliminar/', views.remove, name='remove'),
]

shipping_addresses/urls.py
from django.urls import path
from . import views 


app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('nuevo', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default')
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from products.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('carrito/', include('carts.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('orden/', include('orders.urls')),
    path('productos/', include('products.urls')),
    path('usuarios/login/', views.login_view, name='login'),
    path('usuarios/logout/', views.logout_view, name='logout'),
    path('usuarios/register/', views.register_view, name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
    <title>Store</title>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% include 'messages.html' %}
        {% block breadcrumb %}
        {% endblock %}
        <div class="row mt-3">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <!-- <script src="static/js/main.js"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/79cbac550d.js" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="col">
  <h4 class="text-center">{{ message }}</h4>
  {% include 'products/snippets/search.html' %}
  {% include 'products/snippets/list.html' %}
</div>
{% endblock %}

templates/messages.html
{% if messages %} 
{% for message in messages %}

<div class="alert alert-dismissible fade show {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %}"
  role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
{% endfor %} 
{% endif %}

templates/navbar.html
{% url 'carts:cart' as cart %}
{% url 'shipping_addresses:shipping_addresses' as shipping_addresses %}
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <div class="container-fluid">
    <a href="{% url 'index' %}" class="navbar-brand">River Store</a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navb">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div id="navb" class="navbar-collapse collapse-hide">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a href="{{ cart }}" class="nav-link {% if request.path == cart %}active{% endif %}">
          Mi carrito
        <span class="fas fa-shopping-cart"></span>
        </a>
      </li>
      <li class="nav-item">
        {% if user.is_authenticated %}
        <a href="{{ shipping_addresses }}" class="nav-link {% if request.path == shipping_addresses %}active{% endif %}">
          Mis direcciones
        <span class="fas fa-location-arrow"></span>
        </a>
        {% endif %}
      </li>
    </ul>
    <ul class="navbar-nav ms-auto">
        {% if user.is_authenticated %}
        <li class="navbar-item"><a href="{% url 'logout' %}" class="nav-link"><span class="fas fa-sign-out-alt"></span>Salir</a></li>
        {% else %}
        <li class="navbar-item"><a href="{% url 'login' %}" class="nav-link"><span class="fas fa-sign-in-alt"></span>Entrar</a></li>
        <li class="navbar-item"><a href="{% url 'register' %}" class="nav-link"><span class="fas fa-user-plus"></span>Registro</a></li>
        {% endif %}
    </ul>
  </div>
  </div>
</nav>